### ISSUE TITLE
Invalid package provider 'snap'

### ISSUE THREAD

**Issue by Swinkid** [kemra102/puppet-snapd#3]
Hey,

I'm new to puppet, so im probably doing something wrong.

Within one of my node.pp's, i've used your example for spotify. Added include ::snapd at the top of the .pp

I get the error "Failed to apply catalog: parameter provider failed on Package[spotify]: invalid provider 'snap'"

any heads up would be great

**Comment by jvacek** [comment]
@Swinkid did you manage to resolve this? What did you do?
